---
title: "Panorama Mundo Covid-19"
output: 
  flexdashboard::flex_dashboard:
    vertical_layout: fill
---
  
```{r setup, include=FALSE}
{library(flexdashboard)
  library(tidyverse)
  library(ggimage)
  library(gganimate)
  library(png)
  library(RCurl)
  library(lubridate)
  library(tmap)
  #devtools::install_github("rpradosiqueira/brazilmaps")
  library(brazilmaps)
  library(readxl)
  library(gridExtra)
  library(ggrepel)
  library(scales)
  library(stringr)
  library(ggthemes)
  library(transformr)
  library(gifski)
  library(RColorBrewer)
  library(grid)
  library(viridis)
  library(hrbrthemes)
  library(pracma)
  library(stringi)
  library(ggsn)
  library(magick)
  library(cowplot)
  library(plotly)
  library(sf)
}

#Metodo2, ele baixa no tempfile
temp <- tempfile()

download.file(url = "https://covid.ourworldindata.org/data/owid-covid-data.csv",destfile = temp)

Mundo = read_csv(temp)
Mundo = Mundo |> 
  rename(totalCases= total_cases, newCases= new_cases, deaths= total_deaths, newDeaths= new_deaths,
         D1= people_vaccinated, D2= people_fully_vaccinated) 

casosMundo_final= Mundo |> 
  filter(location!="South America", location!="European Union", location!="North America", location!="Europe", location!="Africa", location!="Asia", location!="World")

casosMundo_final0 = casosMundo_final

pop_mun = casosMundo_final0 |> 
  distinct(location, population)

casosMundo_final0 = casosMundo_final0 |> 
  group_by(date) |> 
  summarise(contagem= n(), newDeaths= sum(newDeaths, na.rm=T), deaths= sum(deaths, na.rm=T), 
            newCases= sum(newCases, na.rm=T), totalCases= sum(totalCases, na.rm=T), D1= sum(D1,   na.rm=T), D2= sum(D2, na.rm=T))

casosMundo_final0$populacao = sum(pop_mun$population, na.rm=T)

casosMundo_final0$MM_casos = round(movavg(casosMundo_final0$newCases, n = 7,type = "s"),0)
  
casosMundo_final0$MM_obitos = round(movavg(casosMundo_final0$newDeaths, n = 7,type = "s"),0)
  
casosMundo_final0$MM_vacina = round(movavg(casosMundo_final0$D1, n=7, type="s"),0)
  
casosMundo_final0$MM_vacina2 = round(movavg(casosMundo_final0$D2, n=7, type="s"),0)
  
########################################################################################

img = readPNG("logo_get_uff_covid.png")
image = image_fill(image_read("logo_get_uff_covid.png"),"none")
raster = as.raster(image)
doses = readPNG("doses.png")

casosMundo_final0$`D1 aplicadas` <- NA
casosMundo_final0$`D2 aplicadas`<- NA
#casosMundo_final0$`DU aplicadas`<- NA
#casosMundo_final0$`D3 aplicadas`<- NA

for (i in 1:length(casosMundo_final0$date)) {
  if(is.na(casosMundo_final0$D1[i]=="True")){
    casosMundo_final0$D1[i]<-0
  }
  if(is.na(casosMundo_final0$D2[i]=="True")){
    casosMundo_final0$D2[i]<-0
  }
  #if(is.na(casosMundo_final0$DU[i]=="True")){
  #  casosMundo_final0$DU[i]<-0
  #}
  #if(is.na(casosMundo_final0$D3[i]=="True")){
  #  casosMundo_final0$D3[i]<-0
  #}
}


for(i in 2:length(casosMundo_final0$date)){
  casosMundo_final0$`D1 aplicadas`[i] <- casosMundo_final0$D1[i]- casosMundo_final0$D1[i-1]
  casosMundo_final0$`D2 aplicadas`[i] <- casosMundo_final0$D2[i]- casosMundo_final0$D2[i-1]
  #casosMundo_final0$`DU aplicadas`[i] <- casosMundo_final0$DU[i]- casosMundo_final0$DU[i-1]
  #casosMundo_final0$`D3 aplicadas`[i] <- casosMundo_final0$D3[i]- casosMundo_final0$D3[i-1]
}

casosMundo_final0$`D1 aplicadas`[1]= 0
casosMundo_final0$`D2 aplicadas`[1]= 0
#casosMundo_final0$`DU aplicadas`[1]= 0
#casosMundo_final0$`D3 aplicadas`[1]= 0

#Somando segunda dose + dose unica
casosMundo_final0$`D2 aplicadas` = casosMundo_final0$`D2 aplicadas` #+ casosMundo_final0$`DU aplicadas`

#base_vacina = casosMundo_final0 |> 
#  group_by(date) |> 
#  summarise(Vacinas= sum(`D1 aplicadas`,`D2 aplicadas`,`DU aplicadas`,`D3 aplicadas`, na.rm=T))


########################################################################################

```

Resumos diários Covid-19
=======================================================================
  
column {data-width=500, .tabset}
-----------------------------------------------------------------------
  
### Casos diários
  
```{r}
casosMundo_final0$`Média móvel` <- round(casosMundo_final0$MM_casos,0)
casosMundo_final0$`Casos novos` <- casosMundo_final0$newCases
casosMundo_final0$Data <- casosMundo_final0$date

g1 <- casosMundo_final0 |> ggplot(aes(x=Data, y=`Casos novos`))+ 
  geom_bar(stat="identity",
           fill="orange")+
  geom_line(aes(y=`Média móvel`),
            col="blue")+
  scale_x_date(date_breaks = "2 month",
               date_labels = "%b/%y")+
  scale_y_continuous(label = scales::label_number(big.mark = ".",
                                                  decimal.mark = ",")) +
  labs(title="Casos diários", y= "Casos Novos", x="data")+
  theme_tufte()+
  theme(plot.title = element_text(hjust = 0.5, size=12, face="bold"),
        text = element_text(size=15))

ggplotly(g1) |> 
   layout(images = list(
     list(source = raster2uri(raster),
          xref = "container",
          yref = "container",
          x = 0.1,
          y = 1,
          sizex = 0.15,
          sizey = 0.15,
          opastate = 1.6)
   ))

```

### Óbitos diários

```{r}
casosMundo_final0$`Média móvel` <- round(casosMundo_final0$MM_obitos,0)
casosMundo_final0$`Óbitos novos` <- casosMundo_final0$newDeaths

g2 <- casosMundo_final0 |> ggplot(aes(x=Data, y=`Óbitos novos`))+ 
  geom_bar(stat="identity",
           fill="orange")+
  geom_line(aes(y=`Média móvel`),
            col="blue")+
  scale_x_date(date_breaks = "2 month",
               date_labels = "%b/%y")+
  scale_y_continuous(label = scales::label_number(big.mark = ".",
                                                  decimal.mark = ",")) +
  labs(title="Óbitos diários", y= "Óbitos Novos", x="data")+
  theme_tufte()+
  theme(plot.title = element_text(hjust = 0.5, size=12, face="bold"),
        text = element_text(size=15))

ggplotly(g2) |> 
   layout(images = list(
     list(source = raster2uri(raster),
          xref = "container",
          yref = "container",
          x = 0.1,
          y = 1,
          sizex = 0.15,
          sizey = 0.15,
          opastate = 1.6)
   ))

```


column {data-width=500, .tabset}
-----------------------------------------------------------------------

### Vacinação diária

```{r}
casosMundo_final0$`Primeira dose` <- casosMundo_final0$`D1 aplicadas`
casosMundo_final0$`Segunda dose ou dose única` <- casosMundo_final0$`D2 aplicadas`

g3 <- casosMundo_final0 |> 
  filter(date>="2021-01-01") |> 
  ggplot(aes(x=Data, y=`Primeira dose`))+ 
  geom_bar(stat="identity",
           fill="orange")+
  geom_bar(mapping= aes(y=`Segunda dose ou dose única`),
           stat="identity",
           fill="red", alpha= 0.6)+
  scale_x_date(date_breaks = "month",
               date_labels = "%b/%y")+
  scale_y_continuous(label = scales::label_number(big.mark = ".",
                                                  decimal.mark = ",")) +
  #ylim(c(0,7000)) +
  labs(title="Aplicação diária de Vacinas", y= "Vacinas",
       x= "data",
       color = NULL) + theme_tufte()+
  theme(plot.title = element_text(hjust = 0.5, size=12, face="bold"),
        text = element_text(size=15))

ggplotly(g3) |> 
   layout(images = list(
     list(source = raster2uri(image),
          xref = "container",
          yref = "container",
          x = 0.1,
          y = 1,
          sizex = 0.15,
          sizey = 0.15,
          opastate = 1.6), 
     list(source = raster2uri(doses),
          xref = "container",
          yref = "container",
          x = 0.08,
          y = 0.75,
          sizex = 0.3,
          sizey = 0.3,
          opastate = 1.6)))
```

### Vacinação diária da 1ª dose

```{r}
casosMundo_final0$`Vacinas aplicadas` <- casosMundo_final0$`D1 aplicadas`

g4 <- casosMundo_final0 |> 
  filter(date>="2021-01-01") |> 
  ggplot(aes(x=Data, y=`Vacinas aplicadas`))+ 
  geom_bar(stat="identity",
           fill="red")+
  scale_x_date(date_breaks = "month",
               date_labels = "%b/%y")+
  scale_y_continuous(label = scales::label_number(big.mark = ".",
                                                  decimal.mark = ",")) +
  labs(title="Aplicação diária de Vacinas de 1ª Dose", y= "Vacina de 1ª Dose",
       x= "data")+ 
  theme_tufte()+
  theme(plot.title = element_text(hjust = 0.5, size=12, face="bold"),
        text = element_text(size=15))

ggplotly(g4) |> 
   layout(images = list(
     list(source = raster2uri(raster),
          xref = "container",
          yref = "container",
          x = 0.1,
          y = 1,
          sizex = 0.15,
          sizey = 0.15,
          opastate = 1.6)
   ))

```

### Vacinação diária da 2ª dose ou Dose Única

```{r}
casosMundo_final0$`Vacinas aplicadas` <- casosMundo_final0$`D2 aplicadas`

g5 <- casosMundo_final0 |>   
  filter(date>="2021-01-01") |> 
  ggplot(aes(x=Data, y=`Vacinas aplicadas`))+ 
  geom_bar(stat="identity",
           fill="blue")+
  scale_x_date(date_breaks = "month",
               date_labels = "%b/%y")+
  scale_y_continuous(label = scales::label_number(big.mark = ".",
                                                  decimal.mark = ",")) +
  labs(title="Aplicação diária de Vacinas de 2ª Dose ou Dose Única", y= "Vacina de 2ª Dose ou Dose Única",
       x= "data")+ 
  theme_tufte()+
  theme(plot.title = element_text(hjust = 0.5, size=12, face="bold"),
        text = element_text(size=15))

ggplotly(g5) |> 
   layout(images = list(
     list(source = raster2uri(raster),
          xref = "container",
          yref = "container",
          x = 0.1,
          y = 1,
          sizex = 0.15,
          sizey = 0.15,
          opastate = 1.6)
   ))
```


Vacinas Covid-19
=======================================================================
  
column {data-width=200}
-----------------------------------------------------------------------

### Primeira dose
  
```{r fig.align='center', echo=FALSE, message=FALSE, warning=FALSE, fig.width = 10}

#pop dos Paises do Mundo 2021 (na coluna Valor)
#pop_Mundo = get_sidra(api="/t/6579/n1/all/v/all/p/last%201")
#casosMundo_final0$populacao= 213317639


#Acumulado das vacinas aplicadas
casosMundo_final0= casosMundo_final0 |> 
  filter(date>= "2021-01-01")
casosMundo_final0$`D1 aplicadas`= as.character(casosMundo_final0$`D1 aplicadas`)
for (i in 1:length(casosMundo_final0$`D1 aplicadas`)){
  if(is.na(casosMundo_final0$`D1 aplicadas`[i]==T)) casosMundo_final0$`D1 aplicadas`[i]="Nao informado"
}
casosMundo_final0= dplyr::filter(casosMundo_final0, D1!="Nao informado")
casosMundo_final0$`D1 aplicadas`= as.numeric(casosMundo_final0$`D1 aplicadas`)

casosMundo_final0$D1_AC= cumsum(casosMundo_final0$`D1 aplicadas`)
casosMundo_final0$D2_AC= cumsum(casosMundo_final0$`D2 aplicadas`)


casosMundo_final0$D2_AC= as.character(casosMundo_final0$D2_AC)
for (i in 1:length(casosMundo_final0$D2_AC)){
  if((casosMundo_final0$date[i]<"2021-01-01")) casosMundo_final0$D2_AC[i]=NA
}
casosMundo_final0$D2_AC= as.numeric(casosMundo_final0$D2_AC)




#Mundo_map <- get_brmap(geo = "state",
#                    geo.filter = list(State = 33),
#                    class = "sf")
#Mundo_map = filter(Mundo_map, nome=="Mundo")

#BaseMundo_aux = casosMundo_final0
#BaseMundo_aux$state = sub(pattern = "/Mundo", replacement = "", x = BaseMundo_aux$state)
#BaseMundo_aux$state = str_to_upper(BaseMundo_aux$state)
#aux_inconsistencia = str_to_upper(aux_inconsistencia)
#Mundo = left_join(Mundo_map, BaseMundo_aux, by = c("nome" = "state"))
#names(Mundo)[1] = "state"


# Criando AS TAXAS
Mundo = casosMundo_final0
Mundo = Mundo |> 
  filter(date== max(date)) |> 
  mutate(taxaD1= round(D1_AC/populacao, 2),
         taxaD2= round(D2_AC/populacao, 2))
         #taxaD3= round(D3_AC/populacao, 2))
         #rotulo= str_c(state, " - ", paste0(round(taxaD1,2)*100, "%")))




gauge(Mundo$taxaD1*100, min = 0, max = 100,
      sectors = gaugeSectors(success=c(80,100),warning = c(40,80),danger = c(0,40),
                             colors = c("Red","Red","Red")),
      symbol = "%")
```

### Segunda dose

```{r fig.align='center', echo=FALSE, message=FALSE, warning=FALSE, fig.width = 10}
gauge(Mundo$taxaD2*100, min = 0, max = 100,
      sectors = gaugeSectors(success=c(80,100),warning = c(40,80),danger = c(0,40),
                             colors = c("Blue","Blue","Blue")),
      symbol = "%")
```


column {data-width=800}
------------------------------------------------------------------

### Vacinação acumulada por tipo de dose

```{r }
casosMundo_final0$`Aplicações primeira dose` <- casosMundo_final0$D1_AC
casosMundo_final0$`Aplicações segunda dose ou dose única` <- casosMundo_final0$D2_AC
#casosMundo_final0$`Aplicações terceira dose` <- casosMundo_final0$D3_AC

g6 <- casosMundo_final0 |> 
  ggplot(aes(x=Data, y=`Aplicações primeira dose`, fill = "Primeira dose"))+ 
  geom_line(col= "red")+
  geom_line(aes(y= `Aplicações segunda dose ou dose única`, fill = "Segunda dose ou dose única"),
            col="blue")+
  #geom_line(aes(y= `Aplicações terceira dose`, fill = "Terceira dose"),
            #col="green")+
  scale_x_date(date_breaks = "month",
               date_labels = "%b/%y")+
  scale_y_continuous(label = scales::label_number(big.mark = ".",
                                                  decimal.mark = ",")) +
  labs(title= "Acumulado de vacinas aplicadas por tipo de dose",
       x= "data",
       y="Vacinas Aplicadas",
       color = NULL) + theme_tufte() +
  theme(legend.position = "top", plot.title = element_text(hjust = 0.5, size=12, face="bold"),
        text = element_text(size=15))

ggplotly(g6) |> 
   layout(images = list(
     list(source = raster2uri(image),
          xref = "container",
          yref = "container",
          x = 0.1,
          y = 1,
          sizex = 0.15,
          sizey = 0.15,
          opastate = 1.6)))



```

